#docker-compose-yml

version: '2'

volumes:
  data-volume: {}

services:

  mysql:
   image: mysql:5.7
   restart: always 
   container_name: mysqldb
   volumes:
    - data-volume:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test
   ports:
     - '3307:3306'

  server:
   container_name: server
   depends_on:
    - mysql
   ports:
    - "54000:54000"
   build:
    context: .
    dockerfile: Dockerfile
   #links:
   # - mysql
  # environment:
  #   TERM=xterm
  # tty: true
  # privileged: true
  # read_only: false
